In [4]:

df= {"Area":[1200,1500,1000,1800,2000,2000],"Bedrooms":[2,3,2,3,4,3], "Bathrooms":[2,2,1,3,3,3], 
     "Location":["Pune","Mumbai","Pune","Delhi","Mumbai","Delhi"], "Price":[6000000,8500000,5000000,9000000,12000000,10000000]}

In [5]:
import pandas as pd
data=pd.DataFrame(df)
data

   Area  Bedrooms  Bathrooms Location     Price
0  1200         2          2     Pune   6000000
1  1500         3          2   Mumbai   8500000
2  1000         2          1     Pune   5000000
3  1800         3          3    Delhi   9000000
4  2000         4          3   Mumbai  12000000
5  2000         3          3    Delhi  10000000

In [6]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Ridge
from sklearn.linear_model import Lasso
from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import mean_squared_error, r2_score

In [7]:
data.isnull().sum()

Area         0
Bedrooms     0
Bathrooms    0
Location     0
Price        0
dtype: int64

In [8]:
data = data.dropna()

Feature Engineering
Convert Categorical Data

Location is categorical, so we apply One-Hot Encoding.

In [9]:
#data=pd.get_dummies(data["Location"])

In [10]:
#data

In [11]:
data = pd.get_dummies(data, columns=['Location'])
#data = pd.get_dummies(data, columns=['Location'], drop_first=True)

In [12]:
data.columns

Index(['Area', 'Bedrooms', 'Bathrooms', 'Price', 'Location_Delhi',
       'Location_Mumbai', 'Location_Pune'],
      dtype='str')

In [13]:
data

,Area,Bedrooms,Bathrooms,Price,Location_Delhi,Location_Mumbai,Location_Pune
0,1200,2,2,6000000,False,False,True
1,1500,3,2,8500000,False,True,False
2,1000,2,1,5000000,False,False,True
3,1800,3,3,9000000,True,False,False
4,2000,4,3,12000000,False,True,False
5,2000,3,3,10000000,True,False,False

Separate Features and Target

In [14]:
X = data.drop("Price", axis=1)
y = data["Price"]

Train-Test Split

In [37]:
X_train, X_test, y_train, y_test = train_test_split(
X, y, test_size=0.2, random_state=42)

Feature Scaling

Scaling is important for models like Linear Regression / Ridge / Lasso.

In [52]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

Model 1: Linear Regression

In [53]:
lr = LinearRegression()

lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)

Model 2: Ridge Regression

In [54]:
ridge = Ridge(alpha=0.1)

ridge.fit(X_train, y_train)

y_pred_ridge = ridge.predict(X_test)

Model 3: Lasso Regression

In [55]:
lasso = Lasso(alpha=0.1)

lasso.fit(X_train, y_train)

y_pred_lasso = lasso.predict(X_test)

Model 4: Random Forest Regressor

In [56]:
rf = RandomForestRegressor(n_estimators=100)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

Model Evaluation

In [57]:
print("Linear Regression R2:", r2_score(y_test, y_pred_lr))

Linear Regression R2: 0.906153846153845

In [58]:
print("Ridge R2:", r2_score(y_test, y_pred_ridge))

Ridge R2: 0.7343397558668119

In [59]:
print("Lasso R2:", r2_score(y_test, y_pred_lasso))

Lasso R2: 0.9308948828698774

In [60]:
print("Random Forest R2:", r2_score(y_test, y_pred_rf))

Random Forest R2: 0.10704000000000002

Predict house price for a new house.

Example:

Area = 1600
Bedrooms = 3
Bathrooms = 2
Location = Pune

In [63]:
new_house = [[1600,3,2,0,0,1]]  # encoded features

new_house = scaler.transform(new_house)

prediction = lasso.predict(new_house)

print("Predicted Price:", prediction)

Predicted Price: [8654591.70204602]

C:\Users\VLT-BNT\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(